### ISSUE TITLE
Please make a portable version of ExifCleaner! (To windows 10 x64)

### ISSUE THREAD

**Issue by johnjohn2050** [szTheory/exifcleaner#101]
Hi Sir, 
First of all I love ExifCleaner, great application
Secondly, Please make a portable version of the app, which isnt require installation and doesn't create folders on appdata / programdata etc. it would be awesome,

Sicnerly yours, John.

ExifCleaner 3.4.0
Electron 10.1.2
win32 10.0.19041
Locale: en-US

**Comment by szTheory** [comment]
Thanks, John! You could try using [exiftool](https://exiftool.org/) directly from the command line, which ExifCleaner depends on anyways. I was considering making a Perl/TK or TCL/TK version to avoid the extra bloat of Electron, but I will probably never have the time for it.
