### ISSUE TITLE
Problem on Mac osx 10.15.7

### ISSUE THREAD

**Issue by freeflyfred** [szTheory/exifcleaner#104]
Work perfectly on my old Mac but on my new Macbook (with Catalina), the app doesn't open. 

![Screen Shot 2020-10-27 at 4 21 57 PM](https://user-images.githubusercontent.com/73558136/97357678-8ca59e00-1870-11eb-9172-7556aad85f24.png)

**Comment by szTheory** [comment]
I wonder if that was an incomplete download or something. Try deleting the old files, downloading the [latest release](https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0) again and reinstalling it.

**Comment by freeflyfred** [comment]
I tried on another Mac (with catalina) and got the same problem. But you confirm me that he should work on 10.15.7?


________________________________
De : szTheory <notifications@github.com>
Envoyé : 27 octobre 2020 16:25
À : szTheory/exifcleaner <exifcleaner@noreply.github.com>
Cc : freeflyfred <freeflyfred@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [szTheory/exifcleaner] Problem on Mac osx 10.15.7 (#104)


I wonder if that was an incomplete download or something. Try deleting the old files, downloading the latest release<https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0> again and reinstalling it.

**Comment by szTheory** [comment]
I just tried reinstalling from the latest release on a Mac with 10.15.7 and it worked. Sorry I'm not sure what the issue is. Are you using the .dmg installer? Also is it installed in your Applications folder? I wonder if you have to right click the app and choose "Open". Maybe you can check your error Console (I think it's called the "Console" app, built in to Mac) and search for ExifCleaner to see if there are any errors logged.

**Comment by freeflyfred** [comment]
I reinstalled it and it finaly work. Sorry for that! Thanks!!!


________________________________
De : szTheory <notifications@github.com>
Envoyé : 27 octobre 2020 16:35
À : szTheory/exifcleaner <exifcleaner@noreply.github.com>
Cc : freeflyfred <freeflyfred@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [szTheory/exifcleaner] Problem on Mac osx 10.15.7 (#104)


I just tried reinstalling from the latest release on a Mac with 10.15.7 and it worked. Sorry I'm not sure what the issue is. Are you using the .dmg installer? Also is it installed in your Applications folder? I wonder if you have to right click the app and choose "Open". Maybe you can check your error Console (I think it's called the "Console" app, built in to Mac) and search for ExifCleaner to see if there are any errors logged.

**Comment by szTheory** [comment]
Awesome! Have a good one
