### ISSUE TITLE
Look into "portable" distribution for Windows with electron-build (like a Linux AppImage or a Mac .app)

### ISSUE THREAD

**Issue by kumar007git** [szTheory/exifcleaner#107]
Is there a portable version? If not, any chance you can provide one for next release? Thanks!

**Comment by szTheory** [comment]
Sorry I don't plan on releasing a version for phones.

**Comment by papb** [comment]
@szTheory I believe what they meant as "portable" is an application that does not have to be installed, it just executes directly. Nothing about phones. I think... 😅

**Comment by szTheory** [comment]
I see. I don't think that will be possible since ExifCleaner depends on the `exiftool` Perl application, so it can't easily be distributed as a single binary application for all platforms. The entire app would have to be written in Perl and then distributed as a single package which would necessitate the use of something like Perl/TK. It's a good idea and would arguably be superior to the bloat of an Electron app, but it's also a lot of work and very different than the current code base.

**Comment by papb** [comment]
@szTheory Do users need to have Perl installed and working on their machines? From the readme, it seems just downloading the app files and executing is enough. If so, at least for Windows providing a portable solution should be easy. Electron-builder has a 'portable' option that will generate a single exe that just works. Not sure for Linux and Mac though.

**Comment by szTheory** [comment]
The Windows version uses a stand-alone Windows executable for Perl provided by the [official exiftool website](https://exiftool.org/), which includes the Perl runtime in the exe itself. Then ExifCleaner opens that .exe in a separate process. So I don't know how I'd unify those into a single exe together. I imagine the electron-builder option you mention only works for normal Electron apps where everything is in either JS or using C extension to node. But I can check into it more.

**Comment by papb** [comment]
Hmm, I see. In that case, I am not sure either, but I would guess it works as well. The way portable works on Windows in electron-builder is it just extracts the standard non-portable thing into a temp directory and runs that. So it should work...

I think you should just try the portable option directly with electron-builder and see if it works. This way you don't waste much time.

**Comment by Bellisario** [comment]
@szTheory, @papb, the compiled and installable application (for Windows) can be extracted into a directory that contains the portable app, too, in a .7z archive. If you unpack it, you will'obtain the portable app...
Of my experience, all Windows Electron apps, can be portable (if Win version, I don't know of others) and if the Perl script runs in the "installed" version (that contains the portable into the .exe), why it doesn't work with the portable one?

Say me if of some problem about the portable and if, you want, ASAP I can get it from the .7z file to the .exe and upload it here, with [this guide](https://www.instructables.com/How-to-create-portable-app/)...

**Comment by Bellisario** [comment]
Successfully runned without istalling it on Windows with my solution: this means that the app can be a portable version! Would you like that I upload my extracted version?

**Comment by szTheory** [comment]
Thanks Bellisario! Do you know if there is a way to integrate the portable app distribution into [electron-build](https://www.electron.build/)? That's what I'm using to package and release the app for different operating systems. People might have also discussed it on their Github issues page.

**Comment by Bellisario** [comment]
Yes @szTheory, you can do a portable version with electron-builder... please read [this article](https://stackoverflow.com/questions/50905886/i-am-trying-to-turn-my-electron-app-to-windows-portable).
Good job!

**Comment by szTheory** [comment]
I've released ExifCleaner [3.5.1](https://github.com/szTheory/exifcleaner/releases/tag/v3.5.1) that adds Windows portable distribution. @kumar007git @Bellisario @papb can you give it a try and let me know how it goes? Thanks!

**Comment by Bellisario** [comment]
It works perfectly for me, @szTheory!

**Comment by AdKiller** [comment]
@szTheory 
@Bellisario 

I suppose ExifCleaner-3.5.1.exe is the portable version not ExifCleaner-Setup-3.5.1.exe ?
Where does it store user settings in portable mode?

Thanks

**Comment by szTheory** [comment]
@AdKiller ExifCleaner doesn't have any stored user settings. The only thing that is customizable is the language and that's detected from the OS setting.
