### ISSUE TITLE
Translation of "ExifCleaner" into German language

### ISSUE THREAD

**Issue by Ne0Genetic** [szTheory/exifcleaner#115]
Hello, I call myself Ne0Gen3tic,

I translate often and gladly, programs into the German language, this of course free of charge, is a matter of honor! With this I would like to give the programmers back a small part of their valuable work on open source projects!

I have translated the .json file (more exactly the strings.json file) from the user directory "AppData\Local\Programs\exifcleaner\resources" into the German language, my translation is thereby translated in "Natural German language" and meets the German language more exactly! 

It sounds better translated, than the previous originals.

If you are interested, please give me your e-mail address or tell me how I can send you the "strings.json" file, as I said, if you are interested in it. If you are not interested in it, that's ok too, then I'll use the German translation only privately😊 thanks a lot!

Nice, friendly greetings from Germany!

Ne0Gen3tic

**Comment by szTheory** [comment]
Thanks for reaching out! There are a couple ways to contribute:

1. Go to this link https://github.com/szTheory/exifcleaner/blob/master/.resources/strings.json and click on the pencil icon
![edit](https://user-images.githubusercontent.com/28652/104971364-724e0d00-59e6-11eb-851b-391da719bfe3.png)
Then paste in your changes and start a new pull request

2. Paste in your strings.json contents directly to the comment box, and surround it with three backticks (```) before and after the code, so that formatting is preserved. Then I'll copy your changes in on your behalf.

Just let me know if you get stuck and I'll guide you through the process.
