### ISSUE TITLE
Add a portable version for Windows

### ISSUE THREAD

**Issue by Bellisario** [szTheory/exifcleaner#118]
Actually, there isn't a Windows portable version, yet.

Please, add a portable version: I'd like to test the app features but without installing it.

**Comment by szTheory** [comment]
Sorry I don't know what a Windows portable version is, can you explain? I use [electron-build](https://www.electron.build/) to build the releases too so it would have to be supported by that tool. There's another ticket for this here [https://github.com/szTheory/exifcleaner/issues/107] so I'll close this one as a duplicate, but if you could comment there it will help. Thanks!
