### ISSUE TITLE
"yarn run update-exiftool" fails executing "mv" command in Windows

### ISSUE THREAD

**Issue by blackcat-917** [szTheory/exifcleaner#126]
Hi, I was updating ExifTool, but the script crashes when he has to move the newer binaries because the command mv doesn't exist in Windows.
Here is the output for vanilla PowerShell Core, but the problem happens also in CMD:

<details>
<summary>Output</summary>
<pre>
---------------------
Moving fresh binaries
---------------------
------> mv exiftool_downloads/Image-ExifTool-12.21/lib .resources/nix/bin
'mv' is not recognized as an internal or external command,
operable program or batch file.
Uncaught exception from user code:
        system mv exiftool_downloads/Image-ExifTool-12.21/lib .resources/nix/bin failed: 256 at C:\Users\tommy\Desktop\Projects\Exifcleaner-parent\exifcleaner\update_exiftool.pl line 103.
        UpdateExifTool::run_command("mv", "exiftool_downloads/Image-ExifTool-12.21/lib", ".resources/nix/bin") called at C:\Users\tommy\Desktop\Projects\Exifcleaner-parent\exifcleaner\update_exiftool.pl line 257
        UpdateExifTool::move_unix_binary("Image-ExifTool-12.21.tar.gz") called at C:\Users\tommy\Desktop\Projects\Exifcleaner-parent\exifcleaner\update_exiftool.pl line 323
        UpdateExifTool::run() called at C:\Users\tommy\Desktop\Projects\Exifcleaner-parent\exifcleaner\update_exiftool.pl line 332
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\tommy\Desktop\Projects\Exifcleaner-parent\exifcleaner>
</pre>
</details>

**Comment by szTheory** [comment]
Thanks for the bug report! Will have to update the Perl script to be portable across Unix and Windows. Can you run it from within the Linux subsystem for Windows?

**Comment by blackcat-917** [comment]
Yes, I can run it

**Comment by szTheory** [comment]
Thanks, I added instructions to the README to run this command from within the Linux Subsystem for Windows
