### ISSUE TITLE
Linux AppImage - Invalid desktop file : exit status 1

### ISSUE THREAD

**Issue by Dyrimon** [szTheory/exifcleaner#130]
As stated in https://github.com/probonopd/go-appimage/issues/139#issuecomment-802158224.

While clicking on the ExifCleaner app icon it opens, after showing this notification:

Invalid desktop file
/home/fedora/Applications/ExifCleaner-3.4.0.AppImage
exit status 1

No other appimage has this error, I'm using the go-appimage via .appimage

`appimaged` developer advised me to open an issue here.

More details to the problem is explained in the stated issue in https://github.com/probonopd/go-appimage/issues/139

**Comment by szTheory** [comment]
Thanks for reporting this! I'll try to cut a new release soon maybe this week.
