### ISSUE TITLE
Remove face tags from Windows Photo Gallery, Digikam, and Picasa

### ISSUE THREAD

**Issue by trymeouteh** [szTheory/exifcleaner#132]
Please have EXIFCleaner also delete face tags. Software such as Picasa, Windows Photo Gallery and Digikam can create face tags which is a special tag that can tell the someone who the person is in a photo.

**Comment by szTheory** [comment]
What's a face tag? Do you know if the [exiftool](https://exiftool.org/) command line program removes it? If Exiftool doesn't support it then ExifCleaner likely won't either.

**Comment by szTheory** [comment]
Closing this until we have more details on the issue
