### ISSUE TITLE
Does not work on macOS 10.15.7

### ISSUE THREAD

**Issue by gitnixpie** [szTheory/exifcleaner#137]
> Check with the developer to make sure ExifCleaner works with this version of macOS.

**Comment by szTheory** [comment]
Thanks for the report! Can you provide a screenshot? Typically you have to right click then pick Open, then allow it to run. I know ExifCleaner does run on 10.15.7 in general, so this might be something more specific happening.

**Comment by gitnixpie** [comment]
The error happened with the zipped version. I downloaded the dmg version now and it works. Thanks!

![Screenshot 2021-04-15 at 17 16 58](https://user-images.githubusercontent.com/81719439/114903558-d5491780-9e0e-11eb-83f7-cfc760046d1c.jpg)

**Comment by szTheory** [comment]
Oh good to hear! Have a good one.
