### ISSUE TITLE
Arbitrary code execution - Update ExifTool to 12.24+

### ISSUE THREAD

**Issue by brandonlou** [szTheory/exifcleaner#140]
I'm not sure what version of ExifTool is being used so if it's already >12.24, please delete this issue. If it isn't, would updating ExifTool to 12.24+ be considered to prevent arbitrary code execution?

Source: [https://twitter.com/wcbowling/status/1385803927321415687](https://twitter.com/wcbowling/status/1385803927321415687)

**Comment by szTheory** [comment]
Thanks for the report! The [latest release](https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0) is on exiftool 12.08. I'll put together a new release over the next few days with an updated exiftool.

**Comment by szTheory** [comment]
@brandonlou I've published a new version 3.5.0 which updates to exiftool 12.25. You can see the release notes [here](https://github.com/szTheory/exifcleaner/releases/tag/v3.5.0). Please let me know if you run into any issues. Thanks again.

**Comment by brandonlou** [comment]
No problem. Thank you for the quick release!
