### ISSUE TITLE
Doesn't work on Arch Linux

### ISSUE THREAD

**Issue by blackcat-917** [szTheory/exifcleaner#144]
Hi, I installed ExifTool on my Arch Linux based distro and it doesn't work (the image metadata doesn't change).
The console throws these errors:
![image](https://user-images.githubusercontent.com/53786619/116814770-b959ab80-ab5a-11eb-8e70-a9293ef5c229.png)
Thanks in advance for the help.

**Comment by szTheory** [comment]
What install method did you use? Sorry I haven't used Arch before.

**Comment by blackcat-917** [comment]
I used the .AppImage installer

**Comment by blackcat-917** [comment]
I noticed that while I'm testing the binary with `namcap` it trows the following errors:
```bash
$ namcap exifcleaner-bin-3.5.1-1-x86_64.pkg.tar.zst
exifcleaner-bin E: ELF files outside of a valid path ('opt/').
exifcleaner-bin W: Referenced library 'libffmpeg.so' is an uninstalled dependency
exifcleaner-bin W: Unused shared library '/usr/lib/librt.so.1' by file ('opt/ExifCleaner/exifcleaner')
exifcleaner-bin W: Unused shared library '/usr/lib/librt.so.1' by file ('opt/ExifCleaner/libGLESv2.so')
exifcleaner-bin W: Unused shared library '/usr/lib/librt.so.1' by file ('opt/ExifCleaner/libffmpeg.so')
exifcleaner-bin W: Unused shared library '/usr/lib/librt.so.1' by file ('opt/ExifCleaner/libvk_swiftshader.so')
exifcleaner-bin E: Dependency perl detected and not included (programs ['perl'] needed in scripts ['opt/ExifCleaner/resources/nix/bin/exiftool'])
```
Does it use libffmpeg or Perl to clean EXIF metadata from files, or it's just something related to the use of electron?

**Comment by szTheory** [comment]
Yes ExifCleaner is powered under the hood by the command line tool [exiftool](https://exiftool.org/) which is written in Perl. The Windows version of ExifCleaner bundles perl in a self-contained .exe, but on Linux or Mac you need to have Perl installed as a dependency. Maybe the era of assuming Perl is installed on every *nix box is coming to an end.

**Comment by blackcat-917** [comment]
I have Perl installed, and I tried to add `perl` as a `PKGBUILD` dependency, now the error of perl disappeared but exifcleaner continues not working.

**Comment by szTheory** [comment]
What's the new error in the web tools inspector? Once you get this working I can roll the instructions back into a README to make it easier for people to install in the future.

**Comment by blackcat-917** [comment]
Arch Linux has a user repository called AUR (just Arch User Repository), this repository is just a bucket containing different `PKGBUILD` files.
PKGBUILD is like a manifest that contains how the package should be built (sometimes it's compiled from source, sometimes not).
PKGBUILD files are maintained by the community so there might be "orphans" sometimes, I "adopted" the package to update it (I thought it was only a question of changing the version and the checksum, but seems that the package didn't work also when there was the old maintainer).
With an AUR helper users can install apps from the AUR just like installing from an official repository.
An AUR helper just invokes `makepkg` on the PKGBUILD (downloading the app), then uses `pacman -U` (which is like using dpkg to install packages) to install the file on the system.
I might have oversimplified the AUR helper's work, but it's just to explain how it works.
Now I'm here because I tried also with the .AppImage file, which has, theoretically, all dependencies bundled and it doesn't work, so I think that the problem is the application itself which doesn't work on Arch Linux.
Sorry for the intricated explanation, tell me if there's something you didn't understand.

**Comment by szTheory** [comment]
Thanks I think I understand. So technically Perl itself should be bundled with the AppImage, rather than having an implicit dependency on a system Perl being installed.

**Comment by blackcat-917** [comment]
Well, it was entirely my fault 😅 .
I have all my system configured to `en_US` except for formats like money currency and time which are in my language.
For Perl, this isn't right and it refuses to do some actions (Perl told me to review the locale settings in the console but I always ignored it thinking that it wasn't important).
Many thanks for paying attention to this error.

**Comment by szTheory** [comment]
Haha glad you got it working!
