### ISSUE TITLE
`node-sass` is deprecated

### ISSUE THREAD

**Issue by blackcat-917** [szTheory/exifcleaner#157]
Hi, I just noticed that [node-sass is deprecated](https://www.npmjs.com/package/node-sass#:~:text=warning%3A%20libsass%20and%20node%20sass%20are%20deprecated.%20while%20they%20will%20continue%20to%20receive%20maintenance%20releases%20indefinitely%2C%20there%20are%20no%20plans%20to%20add%20additional%20features%20or%20compatibility%20with%20any%20new%20css%20or%20sass%20features.%20projects%20that%20still%20use%20it%20should%20move%20onto%20dart%20sass.).
This isn't a big problem because the project will still receive "maintenance releases", but the README suggests moving to [dart-sass](https://sass-lang.com/dart-sass).
Also, for some reason, node-sass doesn't compile on my machine with node 16 and from the stack trace, it seems related to this dependency.

**Comment by szTheory** [comment]
@blackcat-917 Thanks for the heads up! I've removed the node-sass dependency (and other deps) and streamlined the CSS in the progress. https://github.com/szTheory/exifcleaner/pull/158
