### ISSUE TITLE
Sometimes flips images

### ISSUE THREAD

**Issue by fishdrum** [szTheory/exifcleaner#168]
I absolutely love this piece of software. It works very well. However, this isn't a huge deal, but it would sometimes flips some images and I am not sure why it does this. Is this intentional? Or is it a bug? This is my first time on Github and I don't really know how this works. Bare with me. But anyways, it does sometimes flip images 90 degrees. Just thought that you guys should know. Keep doing what you're doing!

---

ExifCleaner 3.6.0
Electron 11.4.4
win32 10.0.19042
Locale: en-US

**Comment by szTheory** [comment]
Thanks for reaching out! As far as I know, some image editing/camera software uses exif metadata to specify an orientation (portrait/landscape), so when you remove that exif metadata it will be shown in the true raw pixel form without an extra rotation. I found this link which has some more background info https://leancrew.com/all-this/2009/04/derotating-jpegs-with-exiftool/ but you can find similar resources by searching for some combination of `exif orientation metadata`

If you use the [exiftool command line program](https://exiftool.org/) directly (which ExifCleaner uses under the hood), you should be able to pick more fine-grained options and remove everything except for the orientation.

**Comment by Loki-L1130** [comment]
@fishdrum Better use jExifToolGUI as would be easier rather than using CLI tool. This is just a suggestion if decide to do as what @szTheory said as above.
