### ISSUE TITLE
Add feature: fast one click exif cleaner

### ISSUE THREAD

**Issue by testertv** [szTheory/exifcleaner#183]
I would like to have an option to select a permanent folder e.g. Download folder. After saving the options, Exif Cleaner can create a Windows/Linux/Mac shortcut. In the future, when I click on this shortcut, all files in the folder will be cleaned without opening Exif Cleaner and drag&drop files.  After cleaning, a message can be displayed in the tray.

Thank you very much for your program!!!

**Comment by szTheory** [comment]
Sorry I don't think I'll add this feature. But you could easily recreate it with a script that runs `exiftool` on the Downloads folder. Then your shortcut could run that script. Check out the usage here https://exiftool.org/
