### ISSUE TITLE
Hide the ribbon menu

### ISSUE THREAD

**Issue by ghost** [szTheory/exifcleaner#192]
It would be grateful to hide the ribbon menu under the View menu by a toggle which controls this option.

**Comment by szTheory** [comment]
What's a ribbon menu? Can you attach a screenshot?

**Comment by Loki-L1130** [comment]
![UX-1](https://user-images.githubusercontent.com/87981739/150664926-8d0fd55f-b8a2-466b-9668-0788cebaf764.png)

**Comment by szTheory** [comment]
I don't quite understand the purpose of this feature, so closing
