### ISSUE TITLE
Control exiftool version

### ISSUE THREAD

**Issue by TomasGutierrez0** [szTheory/exifcleaner#20]
I noticed in your `package.json` you use
```json
"dist-exiftool": "^10.53.0",
"node-exiftool": "^2.3.0"
```
Both dependencies were last updated in 2017 and it appears it uses exiftool **10.53** (Released May 17, 2017) but `exiftool`'s latest version is **11.89** (Released Feb 25, 2020)

I think it's important to be able to keep `exiftool` up to date, newer versions contain fixes, improvements and updates Exif version. Maybe you should look into other ways to include `exiftool` so you don't depend on someone else to keep it upto date.

**Comment by szTheory** [comment]
Thanks for the feedback! The app doesn't use the `exiftool` binary that is packaged with `dist-exiftool` or `node-exiftool` packages. The binaries come from the `.resources` dir within the project. I found out the .gitignore template was excluding them and fixed that with e3ae0bdeddbc0a9e521c645a7c451d8a88f0e3a2. You can find more information here https://github.com/szTheory/exifcleaner/issues/20

**Comment by szTheory** [comment]
@TomasGutierrez0 FYI I added a script to keep `exiftool` up to date with every new release in [this pull request](https://github.com/szTheory/exifcleaner/pull/64). It also verifies the checksum of the binaries. So the next release of ExifCleaner (v3.3.1) will bump `exiftool` to the latest 12.01.
