### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Alosy77** [szTheory/exifcleaner#50]
Hello!

I am an English Studies major from Spain. Would you be interested in a Spanish translation of Exif Cleaner? If so, please leave a contact email.

**Comment by szTheory** [comment]
Thanks yes that would be great! I'll need a little time to look into how to set up i18n for the app. I'll probably do it so that it's as simple as creating a pull request where users can edit a strings file for each language. Do you have any experience doing i18n before? If so, what systems do you suggest? Just a heads up it might take me a bit before I'm ready to get back to you, but this is on my radar now.

**Comment by Alosy77** [comment]
I am glad you want to do it.

I have never done anything in i18n. Only have experiencie with Poedit and Trados. I would learn about it if need be.

**Comment by szTheory** [comment]
@Alosy77 Hi, I just got this ready for you. All you have to do is go to https://github.com/szTheory/exifcleaner/blob/master/.resources/strings.json then click on "Edit this file" and add an entry for Spanish underneath the French.

So for example, where it says

```json
	"empty.title": {
		"en": "No files selected",
		"fr": "Aucun fichier sélectionné"
	},
```

```json
	"empty.title": {
		"en": "No files selected",
		"fr": "Aucun fichier sélectionné",
                "es": "Spanish translation here"
	},
```
and repeat that pattern for each of the entries. That's probably the easiest way to contribute. If you want to be able to see all of your translations working in a live app before submitting, you can also do this:

1. Fork the project on Github
2. Follow the directions [here](https://github.com/szTheory/exifcleaner#run-the-app-in-dev-mode) to get ExifCleaner running in development mode on your computer
3. Then update the `strings.json` file as mentioned above, and quit the program and relaunch it to see your changes. When you're finished, commit your changes from the command line with for example `git commit -am "Finished adding translations"`. Then run `git push origin master`, and go to the project URL your forked it to (for example https://github.com/Alosy77/exifcleaner` and click the button to open a new Pull Request.

Let me know if you run into any issues, I can guide you through the process if you get stuck.

**Comment by szTheory** [comment]
Completed in #78
