### ISSUE TITLE
File -> Settings menu item does nothing

### ISSUE THREAD

**Issue by Tox86** [szTheory/exifcleaner#6]
Hello everyone, so i can open:
![settings](https://user-images.githubusercontent.com/7013508/72166501-1f3f8400-33a8-11ea-8300-f03e0e6ea317.gif)

Cheers

**Comment by szTheory** [comment]
There are currently no Settings for the app. It's just drag and drop. I could remove the Settings menu item for now to make it less confusing.

**Comment by szTheory** [comment]
Fixed in 3.0.0 https://github.com/szTheory/exifcleaner/releases/tag/v3.0.0
