### ISSUE TITLE
Some file names such as Japanese are not processed correctly.

### ISSUE THREAD

**Issue by AKKED** [szTheory/exifcleaner#61]
If the file name contains Japanese (Exp: あいう... , アイウ... , ｱｲｳ... , １２３... , 日本語...) or Korean (Exp: 조선말...) characters, it will not be processed correctly.

I feel like I'm having a problem with handling multi-byte characters.

I tried the following file names, but none of them completed successfully:
あ.jpeg
ア.jpeg
ｱ.jpeg
１.jpeg
日本語.jpeg
조선말.jpeg

	---

ExifCleaner 3.2.0
Electron 7.1.9
win32 10.0.18363
Locale: ja

**Comment by szTheory** [comment]
Thank you. This is a known issue with `exiftool` on Windows see https://github.com/szTheory/exifcleaner/issues/17 and https://github.com/szTheory/exifcleaner/issues/59. I don't have a fix yet. I'm too busy to take this on at the moment, but hopefully someone can help identify a fix and let me know. Then I will add it to ExifCleaner so it works for everyone.

**Comment by szTheory** [comment]
@AKKED  Sorry for the delay, but I've finally fixed this in [v3.3.1](https://github.com/szTheory/exifcleaner/releases/tag/v3.3.1). Please let me know if you encounter any further issues.

**Comment by AKKED** [comment]
@szTheory 
All file names that were not processed successfully in v3.2.0 were processed successfully in v3.3.1.
Thank you very much.

---

ExifCleaner 3.3.1
Electron 9.0.0
win32 10.0.18363
Locale: ja

**Comment by szTheory** [comment]
@AKKED Hi, I was wondering if you'd be interested in translating ExifCleaner to Japanese. I've made it very easy, all you have to do is go to https://github.com/szTheory/exifcleaner/blob/master/.resources/strings.json and click on "Edit this file" and add an entry for Japanese underneath the other ones. Full instructions are [here](https://github.com/szTheory/exifcleaner#adding-a-translation).

**Comment by AKKED** [comment]
@szTheory Hello, Japanese translation is complete. Please check.
https://github.com/szTheory/exifcleaner/pull/72
