### ISSUE TITLE
Class "Dock" is only available in macOS, but called also in Windows

### ISSUE THREAD

**Issue by m1chu** [szTheory/exifcleaner#75]
### Problem #1
When you try to build an application in dev mode on Windows using the current `HEAD` from `master` branch you will see the following error:

```
  TypeError: Cannot read property 'setMenu' of undefined
      at setupMenu (webpack-internal:///./src/main/menu.ts:40:55)
      at setup (webpack-internal:///./src/main/index.ts:22:60)
```

**The application doesn't start**.

It seems that the problem is caused by calling an `app.dock` in `menu.ts`. This class and its methods are available only in macOS as mentioned [here](https://www.electronjs.org/docs/tutorial/macos-dock).

### Potential fix of #1
```
if (isMac()) app.dock.setMenu(dockMenu());
```

### Problem #2 
[The same type of problem](https://www.electronjs.org/docs/api/dock) occurs when deleting metadata.

```
  TypeError: Cannot read property 'bounce' of undefined
      at updateDockBounce (webpack-internal:///./src/main/dock.ts:61:55)
      at IpcMainImpl.eval (webpack-internal:///./src/main/dock.ts:32:9)
      at IpcMainImpl.emit (events.js:228:7)
      at WebContents.<anonymous> (electron/js2c/browser_init.js:173:7846)
      at WebContents.emit (events.js:223:5)
```

### Potential fix of #2 
In `dock.ts` change:
```
function updateDockBounce(): void {
	app.dock.bounce("critical");
}
```
to:
```
function updateDockBounce(): void {
	if (isMac()) app.dock.bounce("critical");
}
```

### Summary
I created [pull request](https://github.com/szTheory/exifcleaner/pull/74) fixing above problems. @szTheory, please look at them and modify if necessary.

**Comment by szTheory** [comment]
Awesome, thank you!
