### ISSUE TITLE
Add a "File -> Open" menu item to select images

### ISSUE THREAD

**Issue by szTheory** [szTheory/exifcleaner#9]
There's should be a "File => Open" menu item as an alternative to dragging and dropping. This is standard for at least macOS apps.

**Comment by totoroot** [comment]
+1
Drag and drop as the only option makes it rather unusable if you are used to not using the mouse much and usually navigating between windows with the keyboard. For it to be usable with keyboard it would be good to also add an ALT + <KEY> menu navigation.
Thank you for your work!

**Comment by szTheory** [comment]
@totoroot I added this feature if you want to take it for a spin
